package com.pursuetao.fayelee0.leetcode.easy;

/**
 * <a href="https://leetcode.com/problems/find-the-difference/">389. Find the Difference (Easy)</a>
 *
 *  Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class Code389 {
    // 1. s[a, b, c] - t[a, b, c, d]
    // 2. a-a = 0, b-b = 0, c-c = 0, d - 0 = d
    public static char findTheDifference1(String s, String t) {
        int N = s.length();
        long ret = t.charAt(N);
        for (int i = 0; i < N; i++) {
            ret -= s.charAt(i);
            ret += t.charAt(i);
        }
        return (char) ret;
    }

    // 1. s[a, b, c] ^ t[a, b, c, d]
    // 2. a^a = 0, b^b = 0, c^c = 0, 0^d = d
    public static char findTheDifference2(String s, String t) {
        int N = s.length();
        char ret = t.charAt(N);
        for (int i = 0; i < N; i++) {
            ret ^= s.charAt(i);
            ret ^= t.charAt(i);
        }
        return ret;
    }
}
